### ISSUE TITLE
Context isn't automatically added anymore

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-editor#50]
With the PR at https://github.com/dini-ag-kim/lrmi-profile/pull/16, the context wasn't automatically embedded anymore although there still is a `default` set like this:

```json
      "default": {
        "@context": [
          "https://w3id.org/kim/lrmi-profile/draft/context.jsonld"
        ]
      }
```

I also added the `definitions` object in the schema and `oneOf` in this PR. Maybe that is the problem.

**Comment by acka47** [comment]
It looks like the problem is `definitions` and/or `oneOf`. The schema version where I only adjusted the context bit is working as expected, see https://skohub.io/editor/?schema=https://raw.githubusercontent.com/dini-ag-kim/lrmi-profile/ed3bf3196108cd48814d237e162c8062e44db15f/draft/schemas/schema.json

**Comment by literarymachine** [comment]
> It looks like the problem is definitions and/or oneOf.

Yes, the top level `oneOf` is the problem here. It isn't that trivial to properly support `oneOf` different object types in the UI, and there is some merging of schemas going on in [Builder](https://github.com/hbz/skohub-editor/blob/50932dd489b540377ea3a97a4acb44d57a463754/src/components/JSONPointerForm/Builder.js#L28-L30) that are most likely causing trouble here and that I won't be able to look into.

Alas, `oneOf` is not necessary for your schema, it actually makes things more complicated than they should be. See https://github.com/dini-ag-kim/lrmi-profile/pull/20 for a fix.

**Comment by acka47** [comment]
Fixed with https://github.com/dini-ag-kim/lrmi-profile/commit/6452adb5704962e7fbf0ccc8ab0e03944555a3ff. Closing.
